### ISSUE TITLE
Translation issue: Shapeshifting Tribulation element orders

### ISSUE THREAD

**Issue by ucddj** [iguanacore/iguana_acs_fix#64]
`Settings/Language/OfficialEnglish/codedictionary.txt`, line 2607: the order of the tribulation is in fact Metal, Wood, Water, Fire, and Earth as attested by `XiaWorld.JobToHumanThunder.GetToilList()`.

**Comment by iguanacore** [comment]
The original line, `此劫五行俱全，金木水火土五种天劫轮流降临` also follows the `g_emElementKind` ordering, with Jin/Mu/Shui/Huo/Tu being in the same order. Unlike the translation, being:
`This tribulation is of all Five Elements, with Metal, Wood, Fire, Water and Earth versions of it descending one after another.`
Since it's just the translation being out of order, it does seem like a simple fix.
